# Generated by Django 5.2.1 on 2025-05-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categotia',
            new_name='Categoria',
        ),
    ]
